[versions]
accompanist = "0.26.5-rc"
agp = "8.0.0-alpha03"
androidx_test = "1.4.0"
appcompat = "1.5.1"
benmanesversion = "0.42.0"
compose = "1.3.0-rc01"
compose_activity = "1.6.0"
compose_compiler = "1.3.2"
compose_material3 = "1.0.0-rc01"
core_ktx = "1.9.0"
dagger = "2.44"
datastore = "1.0.0"
destinations = "1.7.22-beta"
espresso = "3.4.0"
hilt_navigation = "1.0.0"
junit = "4.13.2"
junit_android = "1.1.3"
kotlin = "1.7.20"
kotlinx_coroutines = "1.6.4"
ksp = "1.7.20-1.0.6"
lifecycle = "2.5.1"
material = "1.6.1"
mockito = "4.0.0"
okhttp = "4.10.0"
play_core = "1.8.1"
retrofit = "2.9.0"
room = "2.4.3"
sdk_min = "26"
sdk_target = "33"
tikxml = "0.8.13"
timber = "5.0.1"

[libraries]
accompanist_flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist_uicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core.ktx" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx.test" }
compose_activity = { module = "androidx.activity:activity-compose", version.ref = "compose.activity" }
compose_icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "compose.material3" }
compose_preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose_test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose_tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose_ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger_kapt = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
destinations = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "destinations" }
destinations_ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "destinations" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt_kapt = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
hilt_navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt.navigation" }
hilt_plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
hilt_test = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
junit = { module = "junit:junit", version.ref = "junit" }
junit_android = { module = "androidx.test.ext:junit", version.ref = "junit.android" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx.coroutines" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle_viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
okhttp_tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
play_core = { module = "com.google.android.play:core-ktx", version.ref = "play.core" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room_ksp = { module = "androidx.room:room-compiler", version.ref = "room" }
room_ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room_runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room_testing = { module = "androidx.room:room-testing", version.ref = "room" }
tikxml_annotation = { module = "com.tickaroo.tikxml:annotation", version.ref = "tikxml" }
tikxml_core = { module = "com.tickaroo.tikxml:core", version.ref = "tikxml" }
tikxml_htmlescape = { module = "com.tickaroo.tikxml:converter-htmlescape", version.ref = "tikxml" }
tikxml_kapt = { module = "com.tickaroo.tikxml:processor", version.ref = "tikxml" }
tikxml_retrofit = { module = "com.tickaroo.tikxml:retrofit-converter", version.ref = "tikxml" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
compose = ["compose_activity", "compose_icons", "compose_material3", "compose_ui", "compose_tooling"]
room = ["room_ktx", "room_runtime"]
tikxml = ["tikxml_annotation", "tikxml_core", "tikxml_htmlescape", "tikxml_retrofit"]

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
versions = { id = "com.github.ben-manes.versions", version.ref = "benmanesversion" }
